### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by rjrochak** [devaslanphp/project-management#100]
Hi Helper Team,

I am facing an issue where, after clicking on any notification, the URL changes to localhost. and How can we setup the application in shared hosting (hostinger). Please help!

Thanks

**Comment by mihaisolomon** [comment]
Hey,

Check in **.env** file to see if you have set up the application url 

```
APP_URL=http://localhost:8000
```

**Comment by mihaisolomon** [comment]
If there are issues reopen this.
