### ISSUE TITLE
multiple mandants

### ISSUE THREAD

**Issue by HeldvonKosmos** [devaslanphp/project-management#107]
Hey there,
is it possible to support multiple mandants with one application?
It would be a nice experience for customers and much easier for hosting.
Thanks in advance!
Jonas

**Comment by HeldvonKosmos** [comment]
I think the feature is discribed here very well:
https://www.ibm.com/topics/multi-tenant

At this moment it is suitable for one company with multiple users.
But multitenancy means, that one application can be used by multiple companys at the same time.

**Comment by mihaisolomon** [comment]
At the moment, we don't have in plan this part. But if you can you can start a PR with this functionality and we can work together on it.

**Comment by HeldvonKosmos** [comment]
Thank you for the offer to work together on this project.
I have some other projects at this moment and it would be very timeconsuming for me to learn eloquent. 
Cause i only write Raw SQL, for compatibility reasons with other tools that i use.
Maybe i will think about a refactoring with the techstack (laravel-inertia-vue) in the future.
