### ISSUE TITLE
Send email notification 

### ISSUE THREAD

**Issue by Gigimurgia** [devaslanphp/project-management#117]
Hi, I can't configure sending notifications via email 

the system does not send any emails even if I have set my provider correctly

can you help me?

**Comment by mihaisolomon** [comment]
Can you show what is the configuration for that provider?

**Comment by Gigimurgia** [comment]
Yes I'm using a Google SMTPS

my env:

MAIL_MAILER=smtp
MAIL_HOST=smtps.aruba.it
MAIL_PORT=587
MAIL_USERNAME=servizio@xxxxxxxx.it
MAIL_PASSWORD=xxxxxxxxxxxx
MAIL_ENCRYPTION=ssl

**Comment by mihaisolomon** [comment]
Can you check the queue? In some cases all the emails that needs to be sent are put in the queue.

**Comment by Gigimurgia** [comment]
the queue shows me some running and Done activities on the notification part but I don't know if they also concern emails or just the notification filament



![Screenshot 2024-05-31 alle 10 54 10](https://github.com/devaslanphp/project-management/assets/64425955/38d2bd6e-f4b3-4685-8910-0dfa4837fd55)

**Comment by mihaisolomon** [comment]
Check if you are one of the watchers of that ticket. In order to get the status update.

**Comment by Gigimurgia** [comment]
I saw and received two emails to change the status of the ticket
However, they don't arrive due to ticket modification, ticket manager appointment, new ticket creation, new user addition... maybe I'm doing something wrong in the helper configuration

**Comment by mihaisolomon** [comment]
Here is the list of all notifications on project:
![image](https://github.com/devaslanphp/project-management/assets/17908506/e0bed797-02ff-453a-bf58-088be0324f8b)

Also you can look on the `Ticket` model on `boot` method. There you can see all the events that are generatiing.

**Comment by Gigimurgia** [comment]
ticketComment had the commented notification function... I was stupid not to check it, thanks for the help now the emails are sent  
Thank you
