### ISSUE TITLE
Images Uploaded Resolve to a 404 location

### ISSUE THREAD

**Issue by mbithy** [devaslanphp/project-management#120]
When you upload an image it brings the image as:

[https://domain/my-profile/storage/1/inHFf5IRTqgANZ1wf2xWpiekxZwGaS-metacGxhdGZvcm0tbG9nby1iaWcucG5n-.png](url)

which is a 404 location because the is no storage folder in public folder

**Comment by mihaisolomon** [comment]
`php artisan storage:link` run this
