### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by adaoss** [devaslanphp/project-management#17]
hi.
I've downloaded code and installed in devilbox normally. Created database, made migration and ran seed command. 

But i cant login to app. Ran php artisan make:filament-user as well, user was created but still unable to login.

I've then disabled f2a auth but no luck so far.

Any idea what might be happening?

Thanks in advance

**Comment by moussazoungrana** [comment]
Typically, when the user creates, a default password is assigned. This means that your password that you created is ignored.
But, normally an email is sent to you to change it.
Have you configured the sending of emails?

![image](https://user-images.githubusercontent.com/73730757/210561653-5201b6c1-5d2c-4f70-a4ea-056027cd1955.png)

**Comment by moussazoungrana** [comment]
Another solution but not really practical is to directly change the password in the database.
To do this, you can use a bcrypt-compatible password generator to generate the hash of the password you want.
And you place this hash directly in the password column of your user.
Normally it should work

[https://bcrypt-generator.com/](url) (link for bcrypt generator)

**Comment by adaoss** [comment]
Thanks Moussa Zoungrana,
i've finally logged in into app.

Since it was an experiment, i haven't configured mail service. 

Onde again , thank you  for your help. I'll now take a look to app.

Kind regards
Adão

**Comment by moussazoungrana** [comment]
@adaoss You're welcome, it was a pleasure :wink:

**Comment by heloufir** [comment]
Hello @adaoss 
In addition to what @moussazoungrana said, I can add that when you configure the application and execute the seeders, a default user is created with the following password: **Passw@rd**

You can see it on the seeder source code DefaultUserSeeder https://github.com/devaslanphp/project-management/blob/0400f3fb936d269b1aacd01fdb590c7ea7341b71/database/seeders/DefaultUserSeeder.php#L22

I will close this issue, but feel free to reopen it if needed.
