### ISSUE TITLE
Activities type

### ISSUE THREAD

**Issue by mihaisolomon** [devaslanphp/project-management#19]
I worked previously on a timesheet app combined with a ticket management. And we had activities attached to the logged hours.  We had something like this

- Programming
- Testing
- Learning
- Research 
- etc ...

It will help on reporting at the end of a month to see how many hours were spent in developing testing etc.

**Comment by heloufir** [comment]
Hello @mihaisolomon 
This is a good idea, I am planning to add a timesheet module to the application (as you can see in the issue there is one for timesheet) 
For the activity type, it's attached to the ticket, so we will have at the end ticket type, priority and activity type?

**Comment by mihaisolomon** [comment]
The activity type will be added to the logged time. Because in a ticket you will have multiple people working on it and they will have different activities.

**Comment by mihaisolomon** [comment]
I will make a PR later this week with what I have in mind.

**Comment by heloufir** [comment]
> The activity type will be added to the logged time. Because in a ticket you will have multiple people working on it and they will have different activities.

Oh I see that makes sens.
I will convert this issue to a task in the roadmap, I think it will give a great value to the app.

Thanks a gain, and feel free to add more details if you want

**Comment by heloufir** [comment]
> I will make a PR later this week with what I have in mind.

Great thanks for your help

**Comment by mihaisolomon** [comment]
Check PR: https://github.com/devaslanphp/project-management/pull/25

**Comment by heloufir** [comment]
I will do it ASAP, thanks for helping

**Comment by heloufir** [comment]
@mihaisolomon 
Just merge the PR, I added some dev:
- `ActivityPolicy` and the related permissions, to secure the `ActivityResource`
- Add the `SoftDeletes` to the `Activity` migration and model

Otherwise the rest is just perfect.
Thanks again
