### ISSUE TITLE
Ticket file upload

### ISSUE THREAD

**Issue by mihaisolomon** [devaslanphp/project-management#20]
Another that is missing is the ability to add files to a ticket, from my point it's a very useful thing to have it. 

![image](https://user-images.githubusercontent.com/17908506/210758126-8f8e8b29-3d81-4812-976a-a02d760d687e.png)

You will have an option to see the attached files and upload others.

**Comment by heloufir** [comment]
> Another that is missing is the ability to add files to a ticket, from my point it's a very useful thing to have it.
> 
> ![image](https://user-images.githubusercontent.com/17908506/210758126-8f8e8b29-3d81-4812-976a-a02d760d687e.png)
> 
> You will have an option to see the attached files and upload others.

Yes totally agree, I am planning to add this feature to the next release, I am already working on it in my local.

**Comment by heloufir** [comment]
The last release (1.1.7) contains the **Attachments** tab
![image](https://user-images.githubusercontent.com/6197875/210863917-51f85827-963f-4d35-a472-9eddc804f03a.png)

The files are stored separately in a folder with the name of the ticket code
![image](https://user-images.githubusercontent.com/6197875/210864131-ed69edbe-89bb-4bd9-8692-012f59345c2c.png)
