### ISSUE TITLE
Any plans for Docker image?

### ISSUE THREAD

**Issue by ItsNoted** [devaslanphp/project-management#23]
Would love to give this a go in a Docker container if possible. 🐳

**Comment by heloufir** [comment]
Hello @ItsNoted 

Yep the application Dockerization is in the project RoadMap, not really right now but will be done ASAP.
I will put this issue as a project task, so you can check when it will be done.

**Comment by heloufir** [comment]
Hello @ItsNoted 
A new PR #45 is just merged into the repository and released (v1.2.2)
And the repository is configured to push a new docker image automatically when a release is created, you can check the image here: [https://hub.docker.com/r/eloufirhatim/helper](https://hub.docker.com/r/eloufirhatim/helper)

If you can test it, and give me your feedback (errors if exists, enhancement, ...) it will be great.

**Comment by matbgn** [comment]
Thanks for the deployment!

Could you please tag the version on docker hub? It will really improve the migration process in a near future.

**Comment by heloufir** [comment]
@matbgn indeed it will be good, thanks for pointing that.
It's done on the last commit on the repo, now the docker hub image will contains the release tag in addition to the latest version.

**Comment by matbgn** [comment]
Many thanks I will prepare a Caprover https://caprover.com/ definition file to able One-click app deployment based on tagged version.
