### ISSUE TITLE
Ticket file upload listing

### ISSUE THREAD

**Issue by mihaisolomon** [devaslanphp/project-management#24]
I looked over the files uploads and it looks nice. 

I'm thinking of making a listing of the files something like this:

![image](https://user-images.githubusercontent.com/17908506/211205834-2cf4aab8-7f7c-430d-a6ef-0bb9d670e209.png)

**Comment by heloufir** [comment]
Hello @mihaisolomon 
So the table need to have the following columns:
- File (the file's name)
- Type (The file's mime, e.g. pdf, docx, ...)
- File size (The file's size)
- Created at (The file's Upload date)

And for the actions, we can have the **Edit** and **Delete**:
- Edit (To edit the file's name)
- Delete (To delete the file)

And I suggest to use `laravel-medialibrary` package of `Spatie`.

What do you think?

**Comment by mihaisolomon** [comment]
Yes. That's the one that I was thinking of. But please put the uploaded files into the `media` table rather then tickets column.

**Comment by heloufir** [comment]
Alright I see now the idea.

I will do it like described above, and yes a table named medias will be used for all the files (managed by spatie/laravel-media)

**Comment by heloufir** [comment]
@mihaisolomon 
I just added the attachments system for tickets based on Spatie media package, and it looks like this:

![image](https://user-images.githubusercontent.com/6197875/212181491-fe3da64b-5b4d-43b6-af0b-5d49332ea586.png)

I pushed all the dev to master so you can check if you want and let me know if it's correct for you.

**Comment by heloufir** [comment]
@mihaisolomon Just a trick, the project has a custom artisan command `php artisan trans:missing {lang}` that take the `{lang}.json` file and compare with other lang json files to automatically translate and add the missing keys from the `{lang}.json` to the others.

E.g.
You can add your new translations into your desired `{lang}.json` for example `fr.json` when you finish execute `php artisan trans:missing fr` then the command will generate the missing translation into `ar.json`, `uk.json`, ... and all the json files
