### ISSUE TITLE
Sprints similar to Jira

### ISSUE THREAD

**Issue by mihaisolomon** [devaslanphp/project-management#28]
I was looking over Jira and I think it will be a good idea to organise the tasks in sprints. Something like bellow:

![image](https://user-images.githubusercontent.com/17908506/211517461-c61bed4e-4c06-4119-bec1-e306373f8877.png)

You can configure your sprint length.

![image](https://user-images.githubusercontent.com/17908506/211518243-cb24a5c3-47a9-4127-ac43-fe2f3ada1116.png)

The ticket listing could become the backlog and the default view will be the kanban board for the sprint (active)

**Comment by heloufir** [comment]
I have the same idea, I think it will be good to have a Scrum module like Kanban, but with sprints of different period (that can be configured).

I will add this issue as a task of the project so we can give more details and ideas before I start dev on it.

**Comment by heloufir** [comment]
- [ ] Sprint schema / model + Project type (Kanban or Scrum)
- [ ] Sprint resource
- [ ] Link Sprints and Epics
- [ ] Update issue form to have Epic / Sprint based on project type
- [ ] Update Kanban page to have sprints if project has type Scrum

**Comment by heloufir** [comment]
FYI

The sprint are managed as a relation manager inside the project resource (when the project type equals "scrum")
![image](https://user-images.githubusercontent.com/6197875/212661517-6b806a42-1f44-4547-b7a7-4318855e61d5.png)

**Comment by mihaisolomon** [comment]
Looks nice. The way I see this is a little different. Not as a projects resource but more like a resource where you can combine different projects. You can add into a sprint tasks from different projects. Because there are cases where you can split your main project in different small projects. Or maybe I'm wrong

**Comment by heloufir** [comment]
@mihaisolomon yep that can be like you said
My idea is like Jira, you can create projects typed Scrum or Kanban and manage them separatly
But also like you said, the platform will provides an option to migrate tickets to another project (when you can combine tickets from multiple projects) and also you can choose Scrum or Kanban to manage your combined project.

**Comment by heloufir** [comment]
And now as we we have 2 types of boards Scrum and Kanban, I added a step "Board" where you will choose you project before showing it's scrum or kanban board based on the project type

![image](https://user-images.githubusercontent.com/6197875/212664524-8fd3c8f2-631e-457f-acdd-2884f037ec80.png)

**Comment by heloufir** [comment]
A view "Scrum" similaire to "Kanban" view is added to handle projects (type equals to scrum)

![image](https://user-images.githubusercontent.com/6197875/212693233-545a6e6f-0ad7-4fdd-8ca3-41ca89619448.png)
