### ISSUE TITLE
Timesheet component missing features

### ISSUE THREAD

**Issue by mihaisolomon** [devaslanphp/project-management#29]
I think we are missing a few things from this component

- [x] Daily/weekly reports on the time logged - PR: https://github.com/devaslanphp/project-management/pull/53
- [x] Logged time split by activity - PR: https://github.com/devaslanphp/project-management/pull/44
- [x] Monthly reports on time logged 
          - PR: https://github.com/devaslanphp/project-management/pull/38
          - PR: https://github.com/devaslanphp/project-management/pull/44
          - https://github.com/devaslanphp/project-management/pull/53
- [ ] Target hours per moth customised per user (maybe)
- [ ] Split hours between lets say billable and non billable 
- [x] Timesheet listing - PR: https://github.com/devaslanphp/project-management/pull/33

If think of anything else please add.

**Comment by heloufir** [comment]
Hmm I see, do you think of a separated dashboard where the user can view / export data as tables / graphs or something else?

**Comment by mihaisolomon** [comment]
Yes, something like that, and a widget in the main one with some basic information like reported hours this month.

**Comment by heloufir** [comment]
Ok I see, so it will like a reporting dashboard giving the user some quick KPI and options to export and view data.

**Comment by mihaisolomon** [comment]
Timesheet listing:

![image](https://user-images.githubusercontent.com/17908506/212033064-a27cc23e-85e0-4f57-9ae6-839015c2830c.png)

Menu:

![image](https://user-images.githubusercontent.com/17908506/212033147-4d7894d8-5cc3-4231-b95a-9afcf0514eb9.png)

**Comment by heloufir** [comment]
That looks good!

**Comment by heloufir** [comment]
@mihaisolomon just tested it with a big comment and it looks like below 
![image](https://user-images.githubusercontent.com/6197875/212176210-fc247536-8ed9-4793-807f-b27998d615f4.png)

I think it would be good to add some limit to the comment column like these:

```php
Tables\Columns\TextColumn::make('comment')
    ->label(__('Comment'))
    ->limit(50)
    ->sortable()
    ->searchable(),
```

**Comment by mihaisolomon** [comment]
I'm working on a small widget, I will fix this part also. Thanks.

**Comment by mihaisolomon** [comment]
The first widget looks something like this:

![image](https://user-images.githubusercontent.com/17908506/212680520-422cf8c7-8473-49c9-aa55-c99480b3f79b.png)

**Comment by heloufir** [comment]
That looks nice, you are using Filament Widgets?

**Comment by mihaisolomon** [comment]
> That looks nice, you are using Filament Widgets?

Yes.

**Comment by heloufir** [comment]
@mihaisolomon 
I will hide the Timesheet menu, so I can publish a new release containing the Scrum board without showing the Timesheet menu for now, that's ok for you?

**Comment by heloufir** [comment]
Just merged the PR #38 
When I go to the Timesheet Dashboard, I got this error
![image](https://user-images.githubusercontent.com/6197875/212697393-fd91da06-9240-4a0b-b466-c4ee8bf96e7e.png)

I think the `DATE_FORMAT` you are using on your SQL Query

**Comment by mihaisolomon** [comment]
What mysql version you are using?

**Comment by mihaisolomon** [comment]
@heloufir Take a look over the timesheet dashboard and see if the error persists. I have the same code running on a server on MariaDb and could not replicate it.

**Comment by heloufir** [comment]
Yep always the same issue, here is the shared issue: [https://flareapp.io/share/Rmr2Qqkm#F108](https://flareapp.io/share/Rmr2Qqkm#F108)

**Comment by heloufir** [comment]
@mihaisolomon 
The issue is the space below 😱 

![image](https://user-images.githubusercontent.com/6197875/213286370-fbb1c82a-a82a-4b4e-84bc-7031d5164f39.png)

**Comment by heloufir** [comment]
I got another issue related to my demo data, I don't really know what is the issue, I think I soft delete an activity somewhere
But I think it will be good to check inside the `foreach ($collection as $item)` if the `$item->activity != null` before adding the assets, what do you think?

![image](https://user-images.githubusercontent.com/6197875/213287393-bc3d91ab-ed32-455f-83f8-27625cc7b48c.png)

**Comment by heloufir** [comment]
@mihaisolomon Any news on this?

**Comment by mihaisolomon** [comment]
Yes, I will make an update later this week with a few more things, that contains the fix for it.

**Comment by mihaisolomon** [comment]
I will close this one because almost all of the components where done. Some of them they don't make sense for this. If you have any other ideas on this please make a new ticket.
