### ISSUE TITLE
Integrity constraint violation when try to create a user that already exists (email)

### ISSUE THREAD

**Issue by denistorresan** [devaslanphp/project-management#30]
If you want to replicate:
1) Login as admin
3) Delete a user
4) Try create a new user with the same email (of the deleted user) and got an error SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

https://flareapp.io/share/LPdlKDbP#F71

**Comment by heloufir** [comment]
Ow sorry for that, I reproduced the issue, I will make sure to resolve this ASAP and let you know.

**Comment by heloufir** [comment]
Hello @denistorresan 
Just added a PR resolving this issue, please make a pull in your local project, execute migrations `php artisan migrate` and then retry.

You can reopen this issue if needed.

**Comment by heloufir** [comment]
Hello @denistorresan 
Just added a PR resolving this issue, please make a pull in your local project, execute migrations `php artisan migrate` and then retry.

You can reopen this issue if needed.
