### ISSUE TITLE
Unable to login with default user when installed from scratch

### ISSUE THREAD

**Issue by denistorresan** [devaslanphp/project-management#31]
Hi,
I tested a fresh installation, and after migrate and db:seed I tryed to login using john.doe@helper.app / Passw@rd and seems not work (login invalid on form).

btw, I suggest to replace on Database\Seeders\DefaultUserSeeder.php the hashed password from:

                'password' => '$2a$12$h/.Jq3QGHYoJBLBo8hw1mOtJOmtU.BVJFbBWFC7XAVXmE5gOjdXV.', // Passw@rd

to:

                'password' => bcrypt('Passw@rd'),

**Comment by heloufir** [comment]
Okey I think this would be the problem, not letting you login with this password (pre-hashed).

I will update and push a new PR containing what you suggested.
