### ISSUE TITLE
Feature request : SSO with OpenID (OIDC)

### ISSUE THREAD

**Issue by matbgn** [devaslanphp/project-management#48]
Would it be possible to implement a more open protocol for single sign-on like OIDC?

The open-source library Passport.js could be a solution if needed.

**Comment by heloufir** [comment]
I will put this idea on the RoadMap project, I think it would be a good idea.

**Comment by matbgn** [comment]
Based on the actual roadmap what will be a reasonable delay? With absolute no guarantee of course.

**Comment by heloufir** [comment]
There is no other high priority task, so I think I will put it as a next step.
So in a week or two based on my free time

**Comment by heloufir** [comment]
FYI
I think I will use this package [https://github.com/jumbojett/OpenID-Connect-PHP](https://github.com/jumbojett/OpenID-Connect-PHP) I have pinned it a few days ago, so I will try it ASAP.

**Comment by heloufir** [comment]
What do you think, just for fun 😄 

![row-1-column-1](https://user-images.githubusercontent.com/6197875/213534095-941ff549-25f7-4015-9772-8a0fde303fe9.png)
![row-2-column-1](https://user-images.githubusercontent.com/6197875/213534097-1b235c10-e62b-4bbc-a85e-252e931ff77d.png)
![row-3-column-1](https://user-images.githubusercontent.com/6197875/213534100-9d161f3e-c3a1-45b9-bbf1-ff7f3184d921.png)
![row-4-column-1](https://user-images.githubusercontent.com/6197875/213534104-22d33360-c7ff-4d06-9d7f-293a58c72f86.png)
![row-5-column-1](https://user-images.githubusercontent.com/6197875/213534107-6cfa1324-e5fe-4a89-ab34-c6a2cf10fcca.png)

**Comment by matbgn** [comment]
🤣 ChatGPT apologies are enormous! 

But personally I will go trough passport. It's a good battlefield tested library and I'm sure that you will be able to connect it with Connect2Id in one or the other way.

**Comment by heloufir** [comment]
Lol yes there I can't even ask again 🤣

Yep, passport for me too is the best choice.

**Comment by heloufir** [comment]
@matbgn any suggestions for local OIDC connect provider to make tests?

**Comment by matbgn** [comment]
An easy and straightforward solution would be to use Authentik (https://github.com/goauthentik/authentik), personally I use Keycloak.

**Comment by heloufir** [comment]
@matbgn 

I just pushed the OIDC Connect function to `dev` branch, before merging it to master, I would like if possible that you test it in your local to check if the logic is good and match your needs.

To make it working in your local environment:
1. Clone the repo: `git clone https://github.com/devaslanphp/project-management-docs.git`
2. Change the branch to `dev`: `git checkout dev`
3. Install dependencies (back & front): `composer install && npm install`
4. Configure your `.env` file based on docs: [https://devaslanphp.github.io/project-management/#/installation?id=configuration](https://devaslanphp.github.io/project-management/#/installation?id=configuration)
5. Configure your database base on docs: [https://devaslanphp.github.io/project-management/#/installation?id=database](https://devaslanphp.github.io/project-management/#/installation?id=database)
6. Configure your OIDC environment variables:

```
# This example is based on Keycloak as an OIDC provider
# Make sure you change it based on your own OIDC provider
OIDC_IS_ENABLED=true
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_DISCOVERY_ENDPOINT=
OIDC_REDIRECT_URI="${APP_URL}/oidc/callback"
OIDC_REALM="myrealm"
OIDC_URL_AUTHORIZE="${OIDC_DISCOVERY_ENDPOINT}/realms/${OIDC_REALM}/protocol/openid-connect/auth"
OIDC_URL_ACCESS_TOKEN="${OIDC_DISCOVERY_ENDPOINT}/realms/${OIDC_REALM}/protocol/openid-connect/token"
OIDC_URL_RESOURCE_OWNER_DETAILS="${OIDC_DISCOVERY_ENDPOINT}/realms/${OIDC_REALM}/protocol/openid-connect/userinfo"
OIDC_SCOPE="openid"
```

If the environment variable `OIDC_IS_ENABLED` equals to `true` a button **OIDC Connect** will be visible in the login page, click on it to authenticate your user based on your OIDC provider.

> Make sure you have already configured the OIDC environment variables before trying to authenticate your used based on your OIDC provider

**Comment by heloufir** [comment]
FYI
To enable / disable login sections (form, oidc and social) you can use the General settings.

![image](https://user-images.githubusercontent.com/6197875/214280415-10fdc86a-c825-41f5-b97a-09725e8d67f4.png)

**Comment by heloufir** [comment]
@matbgn any news about this?

**Comment by heloufir** [comment]
> Finally I managed to deploy it on Caprover and made a PR on the community for its basic installation as a reward (sorry for the delay) see [caprover/one-click-apps#888](https://github.com/caprover/one-click-apps/pull/888)
> 
> Next I'll try with OIDC and get back to you or make a new issue specifically for that if needed, but I don't mind so.

That's great, thanks for your help!



> As promised the coffee is on its way, enjoy! ☕

Thanks a lot mate! don't hesitate if you need any help, I have a lot to do, but I can help on my free time
