### ISSUE TITLE
Same Ticket Prefix in Multiple Projects

### ISSUE THREAD

**Issue by OTECMarkus** [devaslanphp/project-management#63]
It is possible to create same Ticket Prefix in multiple Projects. I dont think thats a desired behavior.

**Comment by mihaisolomon** [comment]
Can you be more explicit? I don't really understand the behaviour?

**Comment by OTECMarkus** [comment]
You can create multiple Projects with the same Prefix:
![image](https://user-images.githubusercontent.com/84412466/224278543-45f55f55-a0f0-4ab8-8d38-84108c76a3e9.png)
![image](https://user-images.githubusercontent.com/84412466/224278579-1f80e30d-a0ae-420f-abc4-221daf48e58a.png)
![image](https://user-images.githubusercontent.com/84412466/224278609-c1e1c7e3-ef62-4108-bb86-c50d7d35f5bf.png)

I think the Prefix should be unique?

**Comment by mihaisolomon** [comment]
I will take a look into it.

**Comment by mihaisolomon** [comment]
Hey, 

Check this PR: https://github.com/devaslanphp/project-management/pull/73

**Comment by kamilst96** [comment]
I didn't notice it's still open. #73 introduced a regression. Linked PR for fix.

**Comment by OTECMarkus** [comment]
Hi,

i am sorry for the late response. Its working, you can close the case.

Best regards Markus

Von: Kamil Stępień ***@***.***>
Gesendet: Samstag, 15. April 2023 03:25
An: devaslanphp/project-management ***@***.***>
Cc: Markus Hofelich ***@***.***>; Assign ***@***.***>
Betreff: Re: [devaslanphp/project-management] Same Ticket Prefix in Multiple Projects (Issue #63)


I didn't notice it's still open. #73<https://github.com/devaslanphp/project-management/pull/73> introduced a regression. Linked PR for fix.
