### ISSUE TITLE
Move Ticket from one Project in another - no change of Prefix

### ISSUE THREAD

**Issue by OTECMarkus** [devaslanphp/project-management#64]
If i move a Ticket from Project1 with Prefix "P1" to Project2 with Prefix "P2", the prefix does not change.

**Comment by mihaisolomon** [comment]
If you want to keep the same number you will have duplicates. For example if you have P1-01 and you move it to P2 (and in here you have some other tickets) you will have duplicates in ticket numbers. Hope it will make sense.

**Comment by OTECMarkus** [comment]
If i create a ticket in "Project 1" which has the Prefix "P1"
![image](https://user-images.githubusercontent.com/84412466/224277888-c4fdcb84-e8db-406b-acd9-532be8304a86.png)
![image](https://user-images.githubusercontent.com/84412466/224277688-4d1759c7-5308-41ed-914a-90743d93cf46.png)

then i move the ticket in "Project 2" which has the Prefix "P2"
![image](https://user-images.githubusercontent.com/84412466/224277831-1ed9b835-5b34-4353-952b-e8779fd41a2d.png)

the Prefix does not change from "P1" to "P2"
![image](https://user-images.githubusercontent.com/84412466/224278097-65aa66d3-88d9-4e30-8cc8-07f450bbe1c7.png)

is this normal behaviour?

**Comment by mihaisolomon** [comment]
Yes. It's a normal behaviour.
