### ISSUE TITLE
Overview User Intials "Image" not correctly scaled

### ISSUE THREAD

**Issue by OTECMarkus** [devaslanphp/project-management#65]
In the ticket overview, there are Images with the intials of the users. I think this is not scaled correct.
![image](https://user-images.githubusercontent.com/84412466/224363034-0b814e71-7033-4090-bba0-b160c6104d70.png)

The problem seems to be in the css class "w-6" and "h-6"
`<img src="https://ui-avatars.com/api/?name=M+H&amp;color=FFFFFF&amp;background=2ebabd" alt="Markus Hofelich" data-popover-target="popover-user-5-640b53faed210" class="w-6 h-6 rounded-full bg-gray-200 bg-cover bg-center">`

**Comment by heloufir** [comment]
Can you do an `npm run build` (or `npm run dev` if you are in dev environment), I think your styles need to be refreshed.

**Comment by OTECMarkus** [comment]
Sorry, unfortunately we could not test it yet because we have to adapt our environment first. My colleague looks for it and I give you then a feedback

**Comment by mihaisolomon** [comment]
I will close this issue. If the problem persists reopen it and we will try to fix it.
