### ISSUE TITLE
New ticket form error if content is null

### ISSUE THREAD

**Issue by denistorresan** [devaslanphp/project-management#7]
I tryed to insert new ticket and I forgot to add a "Ticket content". In this case there's an SQL exception due to content cannot be null

![immagine](https://user-images.githubusercontent.com/1846826/209118763-eacd1d68-1eda-426c-a6c5-3101fc72f46d.png)

**Comment by heloufir** [comment]
@denistorresan Thanks for reporting this issue.
The last release (1.1.4) contains a fix for this bug.

**Comment by heloufir** [comment]
I would love, any suggestions or help are always welcome 😁
