### ISSUE TITLE
Image in Ticket

### ISSUE THREAD

**Issue by Memurame** [devaslanphp/project-management#78]
When I enter an image in a ticket and then save it then it just shows an error and the uploaded image cannot be displayed.
I use the current version

Attached are a few pictures with the error and info.

![PuTTY](https://user-images.githubusercontent.com/15847494/233019625-29304b4e-e486-49a8-8606-ee628e13dae9.png)
![2023-04-19 10_32_51-Ticket bearbeiten - BEBV Project](https://user-images.githubusercontent.com/15847494/233019627-9d1eee02-bb19-4d2c-b9ce-2dc45f87b2e0.png)
![2023-04-19 10_33_18-Ticket ansehen - BEBV Project](https://user-images.githubusercontent.com/15847494/233019630-97472133-4eeb-47f0-b548-e2cf6e4058d6.png)
![2023-04-19 10_33_27-Not Found](https://user-images.githubusercontent.com/15847494/233019634-858b039b-3396-48ad-9edc-e7e88fa9aa62.png)
![2023-04-19 10_36_11-public - BEBV Cyon - WinSCP](https://user-images.githubusercontent.com/15847494/233019637-be21f101-0088-4873-9be7-d1d5fc6f7ab8.png)

Can anyone help me with this?

Thx

**Comment by heloufir** [comment]
did you run the command `php artisan storage:link` in your project?

**Comment by Memurame** [comment]
Ah, thank you very much. 
I had not executed this command.

It was not described in the installation instructions.

Thank you, it works.

**Comment by heloufir** [comment]
Oh ok, I will check the documentation 👍
