### ISSUE TITLE
Save filter

### ISSUE THREAD

**Issue by Memurame** [devaslanphp/project-management#79]
It would still be good if the filter could be saved.
This way, only the tickets that are still open could be displayed. Or another option would be if the ticket statuses could be set to show or hide tickets with the corresponding status in the list.

![2023-04-19 10_43_40-Ticket - BEBV Project](https://user-images.githubusercontent.com/15847494/233020778-b67ccd19-1282-40af-8e23-83497e16c900.png)

![2023-04-19 10_46_43-Ticket Status bearbeiten - BEBV Project](https://user-images.githubusercontent.com/15847494/233020976-4ca4dd39-907e-4977-9e03-6465605261b7.png)

**Comment by heloufir** [comment]
Yes, I have the same idea but still working on how I can implement this on the Filament tables, and also for the tickets page.
I'll let you know

**Comment by Memurame** [comment]
I have found something. Have it as PR

**Comment by mihaisolomon** [comment]
Resolved in this PR: https://github.com/devaslanphp/project-management/pull/81
