### ISSUE TITLE
I need your help 

### ISSUE THREAD

**Issue by CyrDna** [devaslanphp/project-management#82]
Hello, I hope you are well.
I have two problems and I want to tell you about them in the hope of finding a solution.
1. I can't receive the verification mails, I get errors.
2. I can't install and run npm in production especially on CPANEL

**Comment by mihaisolomon** [comment]
Hey,

1/ Can you put here the errors that you get, so we know how to guide you.
2/ You compile it and upload it manually in the hosting.

**Comment by CyrDna** [comment]
file:///home/hlgs4475/public_html/Helper/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hlgs4475/.npm/_logs/2023-05-05T14_08_39_106Z-debug.log
[hlgs4475@hug Helper]$

**Comment by mihaisolomon** [comment]
I tested on my local machine and could not reproduce the issue. Can you put here all the steps that you made to get this and also attach the report here, this report `/home/hlgs4475/.npm/_logs/2023-05-05T14_08_39_106Z-debug.log`

**Comment by CyrDna** [comment]
Hello in local ( xampp) everything works but in production ( Cpanel) I have errors.
Moreover I don't know how to configure stmp 
The connection could not be established with the host "smtp.mailtrap.io:2525" : stream_socket_client() : Could not connect to smtp.mailtrap.io:2525 (Connection refused).

**Comment by mihaisolomon** [comment]
I think the port 2525 it's blocked by the hosting company. Try to contact them.

**Comment by mihaisolomon** [comment]
If the problem still persists reopen it with a complete error log.
