### ISSUE TITLE
i have a issue need clarification

### ISSUE THREAD

**Issue by r-chandrakumar** [devaslanphp/project-management#83]
my project run only with artisan command. not running by http://localhost/project-management/public . please help me with solve the issue

**Comment by mihaisolomon** [comment]
You need to run php artisan:serve inside the folder. Or you can create a virtual host on you xammp/mamp etc. Or you can use valet.

**Comment by mihaisolomon** [comment]
I will close this ticket. If the issue still persists please reopen it.
