### ISSUE TITLE
Feature Request: Log Time Improovements

### ISSUE THREAD

**Issue by denistorresan** [devaslanphp/project-management#9]
While Time Tracking is an important feature, and a single task can be completed in different moments or days, I suggest you to improove the time log functionality in two ways:

**1) Add Comment on Time Log**

![immagine](https://user-images.githubusercontent.com/1846826/209312138-8416cba9-b8b4-47ad-a5bc-415b33eb8479.png)

and display data on Time Logged Tab and on Export Time CSV.

**2) Expose the "Log Time" Button out of three dots menu.**

![immagine](https://user-images.githubusercontent.com/1846826/209311204-f09ed0ef-3ff1-4883-9424-e909036df9b4.png)

**Comment by heloufir** [comment]
@denistorresan great idea, I will definitly add this feature for the next realease.
I think it will be done in a few days from now, I will let you know when published as a release.

Thanks for your help

**Comment by denistorresan** [comment]
Another suggestion, but maybe it's more complicated is to add that functionality directly on Comment Tab, like do GitLab.
Infact, on gitlab, when you comment an issue you can write something like "/spend 30m" that means that the comment also add 30 minutes with that comment to Time Log.

Here an example:
![immagine](https://user-images.githubusercontent.com/1846826/209326879-802939e4-dd71-475b-b1d4-9a41ac54fc2a.png)

and just a suggestion, can be done something like this:

![immagine](https://user-images.githubusercontent.com/1846826/209327068-659de713-5b2b-4826-979a-59ce0dbcf65a.png)

**Comment by heloufir** [comment]
Yes I see, I will add this feature too, in my roadmap I have it, it's actions on the editor of comments:
- time: /spend
- tag tickets: /ticket
- ...

Like in discord, but I think it will be in the release 2.x because it will take a longer time.

But great idea really thanks for your help.

**Comment by heloufir** [comment]
Hello @denistorresan 

FYI
I just published a new release containing the comment field for ticket hours logging.
And also I created a new ticket #12 to reference your idea for adding actions into the comment field.

**Comment by denistorresan** [comment]
great! thank you!
