### ISSUE TITLE
Maximizing performance

### ISSUE THREAD

**Issue by Kazturin** [devaslanphp/project-management#90]
Hello. Everything is well thought out, but it works slowly. What tips do you have for maximizing performance?

![Screenshot_5](https://github.com/devaslanphp/project-management/assets/71196888/16adc66b-c4f5-4b9e-95f2-c87dd547fc24)

**Comment by mihaisolomon** [comment]
Can you put also the page where you see this? It's hard to give you tips for optimizing it based only on the picture.

**Comment by Kazturin** [comment]
> Can you put also the page where you see this? It's hard to give you tips for optimizing it based only on the picture.

In an empty project, all pages load in 1.8-2 seconds. Is it possible to improve loading time to 1s?

**Comment by mihaisolomon** [comment]
I will check it out.

In my server (production) with data the load time on all the pages it's the same.

**Comment by mihaisolomon** [comment]
I check the tables to make sure they are indexed, on that side everything is okay. The only thing that puts extra load is the library that is used for creating the interface and all the interactions. 
From my point of view is a decent load time, if this it will become a problem we will address it.
