### ISSUE TITLE
Epic

### ISSUE THREAD

**Issue by Kazturin** [devaslanphp/project-management#91]
What is Epic?

![Screenshot_6](https://github.com/devaslanphp/project-management/assets/71196888/e3e62876-26f2-4f55-a9c1-8f5905c886cb)

**Comment by mihaisolomon** [comment]
Epic is a larger piece of work that is broken down into multiple smaller work items called user stories. In Agile, Backlog serves the purpose of a storage place for all future work items that may or may not be delivered by a team. In Kanban, it is the leftmost column on a Kanban board.

**Comment by Kazturin** [comment]
> Epic — это более крупная часть работы, которая разбита на несколько более мелких рабочих элементов, называемых пользовательскими историями. В Agile бэклог служит местом хранения всех будущих рабочих элементов, которые могут быть доставлены или не доставлены командой. В Канбане это крайний левый столбец на доске Канбан.

Thanks a lot
